<?php

namespace LaraGram\Sentinel\Telegram;

use LaraGram\Sentinel\Contracts\EntriesRepository;
use LaraGram\Sentinel\Storage\EntryQueryOptions;
use LaraGram\Support\Facades\Process;
use LaraGram\Support\Str;
use RuntimeException;

use function LaraGram\Support\php_binary;

class Simulator
{
    /**
     * Create a new simulator.
     *
     * @param  \LaraGram\Sentinel\Contracts\EntriesRepository  $entries
     * @return void
     */
    public function __construct(
        protected EntriesRepository $entries,
    ) {
    }

    /**
     * Run an update through the bot in a separate process.
     *
     * @param  array  $update
     * @param  string|null  $connection
     * @param  string  $mode  "dry" answers every API call locally, "live" really sends them.
     * @return array{id: string, mode: string, exit_code: int|null, output: string, duration: float, entries: array}
     */
    public function run(array $update, ?string $connection = null, string $mode = 'dry'): array
    {
        if ($mode === 'live' && ! config('sentinel.playground.allow_live')) {
            throw new RuntimeException('Live simulations are disabled. Enable sentinel.playground.allow_live to send real API calls.');
        }

        $id = (string) Str::orderedUuid();
        $started = hrtime(true);

        $server = [
            'REQUEST_TIME_FLOAT' => microtime(true),
            'REQUEST_TIME' => time(),
            'HTTP_USER_AGENT' => 'Sentinel Playground',
            'REMOTE_ADDR' => '127.0.0.1',
        ];

        if ($connection && ($secret = config("bot.connections.{$connection}.secret_token"))) {
            $server['HTTP_X_TELEGRAM_BOT_API_SECRET_TOKEN'] = $secret;
        }

        $result = Process::path(base_path())
            ->env([
                'SENTINEL_SIMULATION' => json_encode(['id' => $id, 'mode' => $mode, 'connection' => $connection]),
            ])
            ->timeout((int) config('sentinel.playground.timeout', 30))
            ->run([
                config('sentinel.playground.php') ?: php_binary(),
                $this->runner(),
                json_encode($update, JSON_UNESCAPED_UNICODE),
                json_encode($server),
            ]);

        $output = trim($result->output()."\n".$result->errorOutput());

        return [
            'id' => $id,
            'mode' => $mode,
            'exit_code' => $result->exitCode(),
            'output' => Str::limit($output, 4000),
            'duration' => round((hrtime(true) - $started) / 1e6, 1),
            'entries' => $this->entries->get(null, EntryQueryOptions::forBatchId($id))->reverse()->values()->all(),
        ];
    }

    /**
     * Get the path of the script that handles one update, writing it when needed.
     *
     * @return string
     */
    protected function runner(): string
    {
        $path = storage_path('framework/sentinel-runner.php');

        $autoload = var_export(base_path('vendor/autoload.php'), true);
        $bootstrap = var_export(base_path('bootstrap/app.php'), true);

        $script = <<<PHP
<?php

// Generated by Sentinel: handles one update the way public/index.php does.

use LaraGram\Request\Request;

define('LARAGRAM_START', microtime(true));

require {$autoload};

\$app = require_once {$bootstrap};

\$app->handleRequest(Request::capture());

PHP;

        if (! is_file($path) || file_get_contents($path) !== $script) {
            if (! is_dir(dirname($path))) {
                mkdir(dirname($path), 0755, true);
            }

            file_put_contents($path, $script);
        }

        return $path;
    }
}
